name: Docker Build and Deploy

on:
  push:
    branches: [develop, staging, main]
  pull_request:
    branches: [develop, staging, main]

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - branch: develop
            environment: development
            ecr_repository: nailit-dev
          - branch: staging
            environment: staging
            ecr_repository: nailit-staging
          - branch: main
            environment: production
            ecr_repository: nailit-prod
    
    # Only run for the matching branch
    if: github.ref == format('refs/heads/{0}', matrix.branch)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate build metadata
      id: meta
      run: |
        echo "build_time=$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')" >> $GITHUB_OUTPUT
        echo "commit_hash=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
        echo "image_tag=${GITHUB_SHA:0:8}-$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repository }}:${{ steps.meta.outputs.image_tag }}
          ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repository }}:latest
        build-args: |
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyDCLRbf1Nf6NxV4PqO_92-q1wE1rCNOaw0
          NEXT_PUBLIC_BUILD_TIME=${{ steps.meta.outputs.build_time }}
          NAILIT_ENVIRONMENT=${{ matrix.environment }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

    - name: Update App Runner service
      run: |
        # Get the service ARN
        SERVICE_ARN=$(aws apprunner list-services \
          --query "ServiceSummaryList[?ServiceName=='nailit-${{ matrix.environment == 'development' && 'dev' || matrix.environment == 'staging' && 'staging' || 'prod' }}'].ServiceArn" \
          --output text)
        
        if [ -n "$SERVICE_ARN" ]; then
          echo "Updating App Runner service: $SERVICE_ARN"
          
          # Start deployment with new image
          aws apprunner start-deployment \
            --service-arn "$SERVICE_ARN" \
            --no-cli-pager
          
          echo "Deployment started for ${{ matrix.environment }} environment"
        else
          echo "No App Runner service found for ${{ matrix.environment }} environment"
        fi

    - name: Output deployment info
      run: |
        echo "🚀 Deployment Summary:"
        echo "Environment: ${{ matrix.environment }}"
        echo "Image: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.ecr_repository }}:${{ steps.meta.outputs.image_tag }}"
        echo "Commit: ${{ steps.meta.outputs.commit_hash }}"
        echo "Build Time: ${{ steps.meta.outputs.build_time }}" 