name: Environment Deployment Strategy

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main, staging, develop]

env:
  NODE_VERSION: '18'

jobs:
  detect-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.detect.outputs.environment }}
      deploy: ${{ steps.detect.outputs.deploy }}
    steps:
      - name: Detect Environment
        id: detect
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For pull requests, use the target branch
            TARGET_BRANCH="${{ github.base_ref }}"
          else
            # For push events, use the current branch
            TARGET_BRANCH="${{ github.ref_name }}"
          fi
          
          if [[ "$TARGET_BRANCH" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "deploy=true" >> $GITHUB_OUTPUT
          elif [[ "$TARGET_BRANCH" == "staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "deploy=true" >> $GITHUB_OUTPUT
          elif [[ "$TARGET_BRANCH" == "develop" ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "environment=feature" >> $GITHUB_OUTPUT
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Lint
        run: npm run lint
        
      - name: Type Check
        run: npx tsc --noEmit
        
      # Add tests when available
      # - name: Run Tests
      #   run: npm test

  validate-schema:
    runs-on: ubuntu-latest
    needs: [detect-environment]
    if: needs.detect-environment.outputs.environment != 'feature'
    environment: ${{ github.event_name == 'push' && needs.detect-environment.outputs.environment || null }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Validate Prisma Schema
        env:
          DATABASE_URL: ${{ github.event_name == 'push' && secrets.DATABASE_URL || 'postgresql://placeholder:placeholder@localhost:5432/placeholder_db' }}
          DATABASE_MIGRATION_URL: ${{ github.event_name == 'push' && secrets.DATABASE_MIGRATION_URL || 'postgresql://placeholder:placeholder@localhost:5432/placeholder_db' }}
        run: npx prisma validate
        
      - name: Generate Prisma Client
        env:
          DATABASE_URL: ${{ github.event_name == 'push' && secrets.DATABASE_URL || 'postgresql://placeholder:placeholder@localhost:5432/placeholder_db' }}
          DATABASE_MIGRATION_URL: ${{ github.event_name == 'push' && secrets.DATABASE_MIGRATION_URL || 'postgresql://placeholder:placeholder@localhost:5432/placeholder_db' }}
        run: npx prisma generate
        
      - name: Test Database Connection
        if: github.event_name == 'push'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_MIGRATION_URL: ${{ secrets.DATABASE_MIGRATION_URL }}
        run: echo "SELECT 1;" | npx prisma db execute --stdin --schema prisma/schema.prisma
        
      - name: Skip Database Connection Test (PR)
        if: github.event_name == 'pull_request'
        run: echo "⏭️ Skipping database connectivity test for pull request (security)"

  deployment-ready:
    runs-on: ubuntu-latest
    needs: [detect-environment, test, validate-schema]
    if: always() && needs.detect-environment.outputs.deploy == 'true'
    steps:
      - name: Deployment Status
        run: |
          echo "🚀 Ready to deploy to: ${{ needs.detect-environment.outputs.environment }}"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "📋 Next steps:"
          echo "  1. Ensure AWS Amplify environment is configured"
          echo "  2. Ensure Neon database branch exists"
          echo "  3. Configure environment variables in AWS Amplify"
          
          if [[ "${{ needs.detect-environment.outputs.environment }}" == "production" ]]; then
            echo "⚠️  PRODUCTION DEPLOYMENT"
            echo "  • Ensure staging tests passed"
            echo "  • Database migration review completed"
            echo "  • Backup verification completed"
          fi

  notify-deployment:
    runs-on: ubuntu-latest
    needs: [detect-environment, test, validate-schema]
    if: failure()
    steps:
      - name: Deployment Failure
        run: |
          echo "❌ Deployment checks failed for: ${{ needs.detect-environment.outputs.environment }}"
          echo "🔍 Review the failed jobs above"
          echo "📋 Common issues:"
          echo "  • Linting errors"
          echo "  • TypeScript compilation errors"  
          echo "  • Prisma schema validation errors" 